### PR TITLE
Update meta.yaml

### PR DESCRIPTION
**Pull request by sphuber**
Checklist
* [x] Used a [fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Comment by ltalirz** [comment]
@sphuber It's important to use forks to propose changes (otherwise you can end up with accidental releases).
I see you ticked the first box, but this looks like you are making the PR from the same repo?

**Comment by sphuber** [comment]
> @sphuber It's important to use forks to propose changes (otherwise you can end up with accidental releases).
> I see you ticked the first box, but this looks like you are making the PR from the same repo?

Thanks for the heads-up. Since the Github interface gives you the option, when proposing a patch, to either commit directly on `master` or go through a separate branch and make a PR, I thought the checkbox was just making sure people are not committing directly. Don't see how you can get accidental releases? Do I need to close this and open a PR from a fork or can we leave this for this time?

**Comment by ltalirz** [comment]
> Don't see how you can get accidental releases?

I'm not aware of the details of the release process for feedstocks myself, just repeating what I've been told here...

> Do I need to close this and open a PR from a fork or can we leave this for this time?

Yes, I suggest we do it the proper way.

**Comment by ltalirz** [comment]
P.S. If you follow the link in the top comment, it says 
> Branches are automatically published.

I.e. I guess we now have a published release/0.6.0 branch that we may want to delete

**Pull request closed without merging**
