### PR TITLE
`kiwipy==0.8.1`

### PR DESCRIPTION
**Pull request by sphuber**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Comment by sphuber** [comment]
Seems like there are some requirements missing on conda:
```
- nothing provides requested aio-pika ~=8.2
- nothing provides requested nest_asyncio ~=1.5,>=1.5.1
- nothing provides requested pamqp ~=3.2
- nothing provides requested pytray >=0.3.4,<0.4.0
```

**Comment by muhrin** [comment]
How did the kiwipy package work on conda before then?  Or is it that the dependencies are on conda but not the versions we want?

Btw, I just noticed that kiwi doesn't need `nest_asyncio` so maybe that's one that we could get rid of.

**Comment by sphuber** [comment]
@muhrin The dependencies are there, but not the more recent version that we require as of `0.8.0`

**Comment by sphuber** [comment]
See the following open PRs on the respective feedstock repo's

* `pamqp`: https://github.com/conda-forge/pamqp-feedstock/pull/5
* `aio-pika`: https://github.com/conda-forge/aio-pika-feedstock/pull/33  Note for this one, there doesn't seem to be an open PR for `aio-pika~=8.0`.
* `pytray`: https://github.com/conda-forge/pytray-feedstock/pull/4

For `nest-asyncio`, weirdly, there already seems to have been a commit to support the latest `1.5.6`: https://github.com/conda-forge/nest-asyncio-feedstock/commit/9fb189cc751bf2dcea0622020e24435553b8a5cc
So don't know why that showed up in the report.

If you say we don't actually need it, I will look into removing it for `0.8.2`. There were some other inconsistencies/inefficiencies in the dependencies that I noticed.

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Pull request merged**
