### PR TITLE
Dependencies: Remove the `nest-asyncio` dependency

### PR DESCRIPTION
**Pull request by sphuber**
This dependency is no longer required.

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by sphuber** [comment]
@conda-forge-admin, please rerender

**Comment by muhrin** [comment]
Do the other items in the checklist need to be done before we merge this?

**Comment by sphuber** [comment]
> Do the other items in the checklist need to be done before we merge this?

There are no "hard" checks. It is just a reminder to the person creating the PR. For example, the second and third item are mutually-exclusive, so technically you couldn't check both and be right.

**Comment by muhrin** [comment]
Roger.   Thanks!

**Pull request merged**
